---
# Source: workflow-examples/charts/webdav/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: webdav
spec:
  type: ClusterIP
  ports:
  - name: http    
    port: 8080
    protocol: TCP
    targetPort: http
---
# Source: workflow-examples/charts/webdav/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav
  labels:
    app: webdav
    release: RELEASE-NAME
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: webdav
      release: RELEASE-NAME
  template:
    metadata:
      labels:
        app: webdav
        release: RELEASE-NAME
    spec:
      containers:
        - name: webdav
          image: "patrit/webdav:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
#          volumeMounts:
#            - mountPath: /media/complete
#              name: complete-volume
      volumes:
        - name: complete-volume
          persistentVolumeClaim:
            claimName: complete-pvc
---
# Source: workflow-examples/charts/webdav/templates/ingress-route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webdav-http
spec:
  host: workflow-examples-webdav.apps.baloise.dev
  path: /
  port:
    targetPort: http    
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: webdav
    weight: 100
  wildcardPolicy: None
